spring.application.name=api-gestion

# Database Connection (PostgreSQL Persistence)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=proyecta_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=proyecta_db
spring.jpa.show-sql=true

# SQL Initialization
spring.sql.init.mode=never

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Dashboard Config
dashboard.ventana-vencimiento=7
