spring.application.name=api-gestion

# Database Connection (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:proyectadb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL Initialization (Disabled for H2 as we use ddl-auto=update)
spring.sql.init.mode=never
# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Dashboard Config
dashboard.ventana-vencimiento=7
