package com.proyecta.api_gestion.service.notification;

import org.springframework.stereotype.Service;

import java.util.Map;
import java.util.Set;

@Service
public class DefaultNotificationTemplateRulesProvider implements NotificationTemplateRulesProvider {
    private static final String VAR_ACTOR_USERNAME = "actorUsername";
    private static final String VAR_DELIVERABLE_NAME = "deliverableName";
    private static final String VAR_DOCUMENT_STATUSES = "documentStatuses";
    private static final String VAR_DOCUMENT_TYPE = "documentType";
    private static final String VAR_ENLACE_TEXTO = "enlaceTexto";
    private static final String VAR_ENTREGABLE_ID = "entregableId";
    private static final String VAR_ENTREGABLE_NOMBRE = "entregableNombre";
    private static final String VAR_ESTADO_ETIQUETA = "estadoEtiqueta";
    private static final String VAR_MENSAJE_INTRO = "mensajeIntro";
    private static final String VAR_MENSAJE_TITULO = "mensajeTitulo";
    private static final String VAR_OBSERVACIONES = "observaciones";
    private static final String VAR_PERIODO = "periodo";
    private static final String VAR_PROJECT_ID = "projectId";
    private static final String VAR_PROJECT_NAME = "projectName";
    private static final String VAR_RECIPIENT_NAME = "recipientName";
    private static final String VAR_RISK_CODE = "riskCode";
    private static final String VAR_RISK_LEVEL = "riskLevel";
    private static final String VAR_STATE = "state";
    private static final String VAR_TARGET_URL = "targetUrl";

    private static final Map<String, TemplateRules> RULES = Map.ofEntries(
            Map.entry("PROJECT_INITIAL_REGISTERED", new TemplateRules("PROJECT_INITIAL_REGISTERED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, VAR_STATE, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_INITIAL_COMPLETED", new TemplateRules("PROJECT_INITIAL_COMPLETED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, VAR_STATE, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_UPDATED", new TemplateRules("PROJECT_UPDATED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, VAR_STATE, "action", "phaseName", "hitoName", VAR_DELIVERABLE_NAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_DOCUMENT_UPLOADED", new TemplateRules("PROJECT_DOCUMENT_UPLOADED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_TYPE, "documentName", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_TYPE))),
            Map.entry("PROJECT_DOCUMENT_DELETED", new TemplateRules("PROJECT_DOCUMENT_DELETED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_TYPE, "documentName", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_TYPE))),
            Map.entry("PROJECT_DELAYED", new TemplateRules("PROJECT_DELAYED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "overdueDeliverables", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "overdueDeliverables"))),
            Map.entry("PROJECT_CLOSED", new TemplateRules("PROJECT_CLOSED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, VAR_STATE, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_ASSIGNMENT_CREATED", new TemplateRules("PROJECT_ASSIGNMENT_CREATED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "assignmentRole", "assignedUsername", VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, "assignedUsername"))),
            Map.entry("DELIVERABLE_EVIDENCE_UPLOADED", new TemplateRules("DELIVERABLE_EVIDENCE_UPLOADED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME))),
            Map.entry("DELIVERABLE_APPROVED", new TemplateRules("DELIVERABLE_APPROVED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME))),
            Map.entry("DELIVERABLE_REJECTED", new TemplateRules("DELIVERABLE_REJECTED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME, "observation", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME, "observation"))),
            Map.entry("OBSERVATION_SUBSANATED", new TemplateRules("OBSERVATION_SUBSANATED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "observationId", VAR_DELIVERABLE_NAME, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "observationId"))),
            Map.entry("PROJECT_BENEFIT_IMPACT_REQUIRED", new TemplateRules("PROJECT_BENEFIT_IMPACT_REQUIRED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, "benefitImpactUrl", VAR_STATE, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_BENEFIT_IMPACT_SUBMITTED", new TemplateRules("PROJECT_BENEFIT_IMPACT_SUBMITTED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, "reviewUrl", VAR_STATE, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_BENEFIT_IMPACT_RESUBMITTED", new TemplateRules("PROJECT_BENEFIT_IMPACT_RESUBMITTED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, "reviewUrl", VAR_STATE, VAR_RECIPIENT_NAME, "previousState", VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("PROJECT_BENEFIT_IMPACT_REVIEWED", new TemplateRules("PROJECT_BENEFIT_IMPACT_REVIEWED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, "aprobado", VAR_OBSERVACIONES, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "aprobado"))),
            Map.entry("RISK_CREATED", new TemplateRules("RISK_CREATED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE, VAR_RISK_LEVEL, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE))),
            Map.entry("RISK_UPDATED", new TemplateRules("RISK_UPDATED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE, VAR_RISK_LEVEL, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE))),
            Map.entry("RISK_TREATED", new TemplateRules("RISK_TREATED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE, VAR_RISK_LEVEL, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE))),
            Map.entry("RISK_DELETED", new TemplateRules("RISK_DELETED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_RISK_CODE))),
            Map.entry("EVIDENCE_VERSION_REVERTED", new TemplateRules("EVIDENCE_VERSION_REVERTED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME, "versionNumber", "motivo", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DELIVERABLE_NAME))),
            Map.entry("ADVANCE_REPORT_UPLOADED", new TemplateRules("ADVANCE_REPORT_UPLOADED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_PERIODO, "fileName", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_PERIODO))),
            Map.entry("ADVANCE_REPORT_VERIFIED", new TemplateRules("ADVANCE_REPORT_VERIFIED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_PERIODO, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_PERIODO))),
            Map.entry("ADVANCE_REPORT_RETURNED", new TemplateRules("ADVANCE_REPORT_RETURNED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_PERIODO, VAR_OBSERVACIONES, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_PERIODO))),
            Map.entry("SECURITY_ROLE_UPDATED", new TemplateRules("SECURITY_ROLE_UPDATED", Set.of("roleCode", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of("roleCode"))),
            Map.entry("SECURITY_USER_UPDATED", new TemplateRules("SECURITY_USER_UPDATED", Set.of("username", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of("username"))),
            Map.entry("CLOSURE_REQUESTED", new TemplateRules("CLOSURE_REQUESTED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "requester", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("CLOSURE_APPROVED", new TemplateRules("CLOSURE_APPROVED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "approver", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("CLOSURE_REJECTED", new TemplateRules("CLOSURE_REJECTED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "rejector", VAR_OBSERVACIONES, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("ENTREGABLE_FECHA_CAMBIADA", new TemplateRules("ENTREGABLE_FECHA_CAMBIADA", Set.of(VAR_PROJECT_ID, VAR_ENTREGABLE_ID, VAR_ENTREGABLE_NOMBRE, "fechaAnterior", "fechaNueva", "justificacion", VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_ENTREGABLE_NOMBRE, "fechaNueva"))),
            Map.entry("ENTREGABLE_DEADLINE_WARNING", new TemplateRules("ENTREGABLE_DEADLINE_WARNING", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ENTREGABLE_NOMBRE, VAR_ENTREGABLE_ID, "diasRestantes", "fechaLimite", VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ENTREGABLE_NOMBRE))),
            Map.entry("ENTREGABLE_OVERDUE_REMINDER", new TemplateRules("ENTREGABLE_OVERDUE_REMINDER", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ENTREGABLE_NOMBRE, VAR_ENTREGABLE_ID, "diasVencido", "fechaLimite", VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ENTREGABLE_NOMBRE))),
            Map.entry("PROJECT_DIRECTOR_ALERT", new TemplateRules("PROJECT_DIRECTOR_ALERT", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "directorName", "projectState", "avanceTotal", "pendingRisksCount", "pendingRisksDetail", "pendingDeliverablesCount", "pendingDeliverablesDetail", "overdueCount", "overdueDetail", "hasMissingDocuments", "missingDocumentsDetail", "projectUrl", "sentBy", "sentAt", VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("VIABILIDAD_UPLOADED", new TemplateRules("VIABILIDAD_UPLOADED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_STATUSES, VAR_MENSAJE_TITULO, VAR_MENSAJE_INTRO, VAR_ESTADO_ETIQUETA, VAR_ENLACE_TEXTO, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_STATUSES))),
            Map.entry("VIABILIDAD_APPROVED", new TemplateRules("VIABILIDAD_APPROVED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_STATUSES, VAR_MENSAJE_TITULO, VAR_MENSAJE_INTRO, VAR_ESTADO_ETIQUETA, VAR_ENLACE_TEXTO, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_STATUSES))),
            Map.entry("VIABILIDAD_RETURNED", new TemplateRules("VIABILIDAD_RETURNED", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_STATUSES, VAR_OBSERVACIONES, VAR_MENSAJE_TITULO, VAR_MENSAJE_INTRO, VAR_ESTADO_ETIQUETA, VAR_ENLACE_TEXTO, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_DOCUMENT_STATUSES))),
            Map.entry("ACTA_CONSTITUCION_REMINDER", new TemplateRules("ACTA_CONSTITUCION_REMINDER", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "diasRestantes", "plazoVencido", "notificarGestor", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME))),
            Map.entry("ADVANCE_REPORT_DUE_NOTIFICATION", new TemplateRules("ADVANCE_REPORT_DUE_NOTIFICATION", Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, "dueDate", "message", "title", VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME)))
    );

    @Override
    public TemplateRules getRules(String eventCode) {
        return RULES.getOrDefault(eventCode, new TemplateRules(eventCode, Set.of(VAR_PROJECT_ID, VAR_PROJECT_NAME, VAR_ACTOR_USERNAME, VAR_RECIPIENT_NAME, VAR_TARGET_URL), Set.of(VAR_PROJECT_ID)));
    }
}
