package com.proyecta.api_gestion.service.notification;

public enum NotificationEventType {
    PROJECT_INITIAL_REGISTERED,
    PROJECT_INITIAL_COMPLETED,
    PROJECT_UPDATED,
    PROJECT_DELAYED,
    PROJECT_CLOSED,
    PROJECT_ASSIGNMENT_CREATED,
    DELIVERABLE_EVIDENCE_UPLOADED,
    DELIVERABLE_APPROVED,
    DELIVERABLE_REJECTED,
    OBSERVATION_SUBSANATED,
    PROJECT_BENEFIT_IMPACT_REQUIRED,
    PROJECT_BENEFIT_IMPACT_SUBMITTED,
    PROJECT_BENEFIT_IMPACT_REVIEWED,
    RISK_CREATED,
    RISK_UPDATED,
    RISK_TREATED,
    CLOSURE_REQUESTED,
    SECURITY_ROLE_UPDATED
}
